theme: jekyll-theme-merlot
title: [Woo-Aras Integration]
show_downloads: ["true"]
github:
  zip_url: https://github.com/hsntgm/woocommerce-aras-kargo/archive/refs/tags/v1.0.9-alpha.zip
  another_url: https://github.com/hsntgm/woocommerce-aras-kargo/archive/refs/tags/v1.0.9-alpha.tar.gz
